### ISSUE TITLE
Can't make tonight's class

### ISSUE THREAD

**Issue by aychang95** [Git-Stuco/GitStucoClass#4]
Hi guys,
We're interviewing head coaches for the track team so the entire track team is required to meet with the interviewee and ask him questions tonight at 6:30pm-7:30pm.  I can get all the information on your stuco website for today right?  Sorry about this.

Andrew Chang

**Comment by Dogfalo** [comment]
Thats fine, thanks for letting us know!

On Thu, Jan 22, 2015 at 4:44 PM, aychang95 notifications@github.com wrote:

> Hi guys,
> We're interviewing head coaches for the track team so the entire track
> team is required to meet with the interviewee and ask him questions tonight
> at 6:30pm-7:30pm. I can get all the information on your stuco website for
> today right? Sorry about this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Git-Stuco/GitStucoClass/issues/4.

## 

Doggy sends his greetings from Mars.
